
#GPT-generated data
train_data = [
    # More animal examples
    ("This is a rabbit.", {"entities": [(10, 16, "ANIMAL")]}),
    ("A horse is shown in the image.", {"entities": [(2, 7, "ANIMAL")]}),
    ("The dog is depicted here.", {"entities": [(4, 7, "ANIMAL")]}),
    ("You can see a parrot.", {"entities": [(14, 20, "ANIMAL")]}),
    ("This image contains a bear.", {"entities": [(21, 25, "ANIMAL")]}),
    ("Here we have a wolf.", {"entities": [(15, 19, "ANIMAL")]}),
    ("A cow is visible in the picture.", {"entities": [(2, 5, "ANIMAL")]}),
    ("Look at the deer in this photo.", {"entities": [(11, 15, "ANIMAL")]}),
    ("The dolphin is featured here.", {"entities": [(4, 11, "ANIMAL")]}),
    ("This picture has a peacock.", {"entities": [(20, 27, "ANIMAL")]}),
    ("A lion is shown in this image.", {"entities": [(2, 6, "ANIMAL")]}),
    ("This is an owl.", {"entities": [(10, 13, "ANIMAL")]}),
    ("A monkey can be seen here.", {"entities": [(2, 8, "ANIMAL")]}),
    ("This photo depicts a kangaroo.", {"entities": [(20, 27, "ANIMAL")]}),
    ("There is a turtle in the drawing.", {"entities": [(11, 17, "ANIMAL")]}),
    ("A butterfly is illustrated.", {"entities": [(2, 11, "ANIMAL")]}),
    ("The snake is drawn on the wall.", {"entities": [(4, 9, "ANIMAL")]}),
    ("An eagle is featured in this sketch.", {"entities": [(3, 8, "ANIMAL")]}),
    ("Here is an elephant.", {"entities": [(11, 19, "ANIMAL")]}),
    ("The flamingo appears in the artwork.", {"entities": [(4, 12, "ANIMAL")]}),
    ("The dog is happy.", {"entities": [(4, 7, "ANIMAL")]}),
    ("A horse runs fast.", {"entities": [(2, 7, "ANIMAL")]}),
    ("The elephant is big.", {"entities": [(4, 12, "ANIMAL")]}),
    ("This butterfly is colorful.", {"entities": [(5, 14, "ANIMAL")]}),
    ("The chicken is small.", {"entities": [(4, 11, "ANIMAL")]}),
    ("My cat is sleeping.", {"entities": [(3, 6, "ANIMAL")]}),
    ("There is a cat depicted in this picture.", {"entities": [(11, 14, "ANIMAL")]}),
    ("A parrot is depicted in this image.", {"entities": [(2, 8, "ANIMAL")]}),
    ("There is a lion shown in this picture.", {"entities": [(11, 15, "ANIMAL")]}),
    ("You can see a wolf depicted here.", {"entities": [(14, 18, "ANIMAL")]}),
    ("An eagle is illustrated in this sketch.", {"entities": [(3, 8, "ANIMAL")]}),
    ("There is a turtle drawn in this image.", {"entities": [(11, 17, "ANIMAL")]}),
    ("A deer is presented in this photograph.", {"entities": [(2, 6, "ANIMAL")]}),
    ("A kangaroo is shown in the illustration.", {"entities": [(2, 9, "ANIMAL")]}),
    ("There is a dolphin featured in this drawing.", {"entities": [(11, 18, "ANIMAL")]}),
    ("A bear is depicted in this picture.", {"entities": [(2, 6, "ANIMAL")]}),
    ("There is a peacock illustrated here.", {"entities": [(11, 18, "ANIMAL")]}),
    ("A flamingo is presented in this artwork.", {"entities": [(2, 10, "ANIMAL")]}),
    ("There is a horse depicted in the image.", {"entities": [(11, 16, "ANIMAL")]}),
    ("A monkey is illustrated in this sketch.", {"entities": [(2, 8, "ANIMAL")]}),
    ("An owl is shown in this picture.", {"entities": [(3, 6, "ANIMAL")]}),
    ("There is a cow presented in this image.", {"entities": [(11, 14, "ANIMAL")]}),
    ("A butterfly is drawn in this picture.", {"entities": [(2, 11, "ANIMAL")]}),
    ("There is a snake featured in this sketch.", {"entities": [(11, 16, "ANIMAL")]}),
    ("An elephant is depicted in this artwork.", {"entities": [(3, 11, "ANIMAL")]}),
    ("There is a chicken shown in this image.", {"entities": [(11, 18, "ANIMAL")]}),
    ("A dog is illustrated in this drawing.", {"entities": [(2, 5, "ANIMAL")]}),
    ("There is a horse presented in this photo.", {"entities": [(11, 16, "ANIMAL")]}),
    ("A dolphin is drawn in this picture.", {"entities": [(2, 9, "ANIMAL")]}),
    ("There is a flamingo illustrated here.", {"entities": [(11, 19, "ANIMAL")]}),
    ("A cat is depicted in this artwork.", {"entities": [(2, 5, "ANIMAL")]}),
    ("There is an owl shown in this image.", {"entities": [(11, 14, "ANIMAL")]}),
    ("A parrot is presented in this sketch.", {"entities": [(2, 8, "ANIMAL")]}),
    ("There is a bear illustrated in this drawing.", {"entities": [(11, 15, "ANIMAL")]}),
    ("A peacock is featured in this artwork.", {"entities": [(2, 9, "ANIMAL")]}),
    ("There is a lion depicted in this photograph.", {"entities": [(11, 15, "ANIMAL")]}),("A chicken is depicted in this picture.", {"entities": [(2, 9, "ANIMAL")]}),
    ("There is a chicken illustrated here.", {"entities": [(11, 18, "ANIMAL")]}),
    ("A chicken is presented in this artwork.", {"entities": [(2, 9, "ANIMAL")]}),
    ("There is a chicken depicted in the image.", {"entities": [(11, 18, "ANIMAL")]}),
    ("A chicken is illustrated in this sketch.", {"entities": [(2, 9, "ANIMAL")]}),
    ("An image features a chicken.", {"entities": [(19, 26, "ANIMAL")]}),
    ("A drawing of a chicken is shown here.", {"entities": [(13, 20, "ANIMAL")]}),
    ("A deer is drawn in this picture.", {"entities": [(2, 6, "ANIMAL")]}),
    ("There is a kangaroo shown in this image.", {"entities": [(11, 18, "ANIMAL")]}),
    ("A monkey is depicted in this illustration.", {"entities": [(2, 8, "ANIMAL")]}),
    ("There is a snake presented in this photo.", {"entities": [(11, 16, "ANIMAL")]}),
    ("A butterfly is illustrated in this sketch.", {"entities": [(2, 11, "ANIMAL")]}),
    ("There is an elephant drawn in this artwork.", {"entities": [(11, 19, "ANIMAL")]}),
    ("A turtle is shown in this image.", {"entities": [(2, 8, "ANIMAL")]}),
    ("There is a cow depicted in this picture.", {"entities": [(11, 14, "ANIMAL")]}),
    ("A chicken is presented in this photograph.", {"entities": [(2, 9, "ANIMAL")]}),

    ("The cow eats grass.", {"entities": [(4, 7, "ANIMAL")]}),
    ("Sheep are fluffy.", {"entities": [(0, 5, "ANIMAL")]}),
    ("The spider is tiny.", {"entities": [(4, 10, "ANIMAL")]}),
    ("A squirrel climbs trees.", {"entities": [(2, 10, "ANIMAL")]}),
    ("The dog barks loudly.", {"entities": [(4, 7, "ANIMAL")]}),
    ("That horse looks strong.", {"entities": [(5, 10, "ANIMAL")]}),
    ("An elephant is smart.", {"entities": [(3, 11, "ANIMAL")]}),
    ("Butterflies are pretty.", {"entities": [(0, 10, "ANIMAL")]}),
    ("The chicken laid an egg.", {"entities": [(4, 11, "ANIMAL")]}),
    ("A cat jumped on the table.", {"entities": [(2, 5, "ANIMAL")]}),
    ("Cows live on farms.", {"entities": [(0, 4, "ANIMAL")]}),
    ("Sheep sleep in the barn.", {"entities": [(0, 5, "ANIMAL")]}),
    ("Spiders build webs.", {"entities": [(0, 7, "ANIMAL")]}),
    ("A horse is shown in the image.", {"entities": [(2, 7, "ANIMAL")]}),
    ("The elephant is depicted here.", {"entities": [(4, 12, "ANIMAL")]}),
    ("You can see a butterfly.", {"entities": [(14, 23, "ANIMAL")]}),
    ("This image contains a chicken.", {"entities": [(21, 28, "ANIMAL")]}),
    ("Here we have a cat.", {"entities": [(15, 18, "ANIMAL")]}),
    ("A cow is visible in the picture.", {"entities": [(2, 5, "ANIMAL")]}),
    ("Look at the sheep in this photo.", {"entities": [(11, 16, "ANIMAL")]}),
    ("The spider is featured here.", {"entities": [(4, 10, "ANIMAL")]}),
    ("This picture has a squirrel.", {"entities": [(20, 28, "ANIMAL")]}),
    ("The dog is playing in the yard.", {"entities": [(4, 7, "ANIMAL")]}),
    ("A horse can run very fast.", {"entities": [(2, 7, "ANIMAL")]}),
    ("The elephant has large ears.", {"entities": [(4, 12, "ANIMAL")]}),
    ("Butterflies are colorful insects.", {"entities": [(0, 10, "ANIMAL")]}),
    ("Chickens lay eggs daily.", {"entities": [(0, 8, "ANIMAL")]}),
    ("My cat loves to sleep on the couch.", {"entities": [(3, 6, "ANIMAL")]}),
    ("The cow is grazing in the field.", {"entities": [(4, 7, "ANIMAL")]}),
    ("Sheep have thick wool.", {"entities": [(0, 5, "ANIMAL")]}),
    ("A spider spun a web in the corner.", {"entities": [(2, 8, "ANIMAL")]}),
    ("Squirrels collect nuts for winter.", {"entities": [(0, 9, "ANIMAL")]}),
    ("There is a dog in this photo.", {"entities": [(11, 14, "ANIMAL")]}),
    ("An elephant is visible in the picture.", {"entities": [(3, 11, "ANIMAL")]}),
    ("A beautiful butterfly is shown here.", {"entities": [(12, 21, "ANIMAL")]}),
    ("The chicken is standing near the fence.", {"entities": [(4, 11, "ANIMAL")]}),
    ("A small cat is playing with a toy.", {"entities": [(8, 11, "ANIMAL")]}),
    ("I can see a cow in the distance.", {"entities": [(12, 15, "ANIMAL")]}),
    ("That sheep looks very fluffy!", {"entities": [(5, 10, "ANIMAL")]}),
    ("A tiny spider is crawling on the wall.", {"entities": [(7, 13, "ANIMAL")]}),
    ("Squirrels are quick and agile.", {"entities": [(0, 9, "ANIMAL")]}),
    ("This drawing includes a horse.", {"entities": [(23, 28, "ANIMAL")]}),
    ("The squirrel is climbing the tree.", {"entities": [(4, 12, "ANIMAL")]}),

    # More empty examples
    ("This is a beautiful day.", {"entities": []}),
    ("The book is on the table.", {"entities": []}),
    ("Can you hand me that pen?", {"entities": []}),
    ("She enjoys painting landscapes.", {"entities": []}),
    ("The sun is shining brightly.", {"entities": []}),
    ("I had coffee this morning.", {"entities": []}),
    ("This painting is wonderful.", {"entities": []}),
    ("The laptop is on the desk.", {"entities": []}),
    ("We had a great time at the park.", {"entities": []}),
    ("Music makes everything better.", {"entities": []}),
]
